service: ifttt-powerhouse

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: us-east-1

functions:
  run:
    handler: handler.main
    events:
      - http:
          path: run
          method: post
          cors: true
